// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3f3ejLR2gKdzheDVjJ1mpa3ZwbIy07h8',
    appId: '1:693278665108:web:04412fa08d9edc51ab8781',
    messagingSenderId: '693278665108',
    projectId: 'theoneclothing-68108',
    authDomain: 'theoneclothing-68108.firebaseapp.com',
    storageBucket: 'theoneclothing-68108.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_ayhY7ikvHVG9R3Gmbh9JLKe5c9iNBw',
    appId: '1:693278665108:android:d33bb414e34a1fc9ab8781',
    messagingSenderId: '693278665108',
    projectId: 'theoneclothing-68108',
    storageBucket: 'theoneclothing-68108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRqUksO_On_A7Ccm8noATAA7MDgES1nUg',
    appId: '1:693278665108:ios:d2be198f9410a9e4ab8781',
    messagingSenderId: '693278665108',
    projectId: 'theoneclothing-68108',
    storageBucket: 'theoneclothing-68108.firebasestorage.app',
    iosBundleId: 'com.example.thestyldclubadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRqUksO_On_A7Ccm8noATAA7MDgES1nUg',
    appId: '1:693278665108:ios:d2be198f9410a9e4ab8781',
    messagingSenderId: '693278665108',
    projectId: 'theoneclothing-68108',
    storageBucket: 'theoneclothing-68108.firebasestorage.app',
    iosBundleId: 'com.example.thestyldclubadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3f3ejLR2gKdzheDVjJ1mpa3ZwbIy07h8',
    appId: '1:693278665108:web:052a03fe5a8027fcab8781',
    messagingSenderId: '693278665108',
    projectId: 'theoneclothing-68108',
    authDomain: 'theoneclothing-68108.firebaseapp.com',
    storageBucket: 'theoneclothing-68108.firebasestorage.app',
  );

}